# Generated by Django 6.0 on 2026-07-26 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name displayed on the filter buttons.', max_length=100)),
                ('slug', models.SlugField(help_text="URL-friendly version of the name (e.g., 'our-dates').", unique=True)),
                ('icon', models.CharField(blank=True, default='fa-solid fa-heart', help_text='Font Awesome icon class for the category button.', max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order for category filter buttons.')),
                ('is_active', models.BooleanField(default=True, help_text='Only active categories are displayed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gallery Category',
                'verbose_name_plural': 'Gallery Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Title of the timeline event (e.g., 'First Meeting').", max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Short romantic subtitle displayed below the title.', max_length=300)),
                ('date_label', models.CharField(help_text="Display label for the date (e.g., 'January 2024').", max_length=100)),
                ('description', models.TextField(help_text='Brief description shown on the card (always visible).')),
                ('expanded_content', models.TextField(blank=True, help_text='Extended content revealed when the card is expanded on click.')),
                ('icon', models.CharField(default='fa-solid fa-heart', help_text='Font Awesome icon class for the timeline marker.', max_length=100)),
                ('emoji', models.CharField(default='💕', help_text='Decorative emoji displayed on the card.', max_length=10)),
                ('image', models.ImageField(blank=True, help_text='Optional photo for this timeline event.', null=True, upload_to='timeline/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order on the timeline (lower = earlier).')),
                ('is_active', models.BooleanField(default=True, help_text='Only active events are displayed on the page.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Timeline Event',
                'verbose_name_plural': 'Timeline Events',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the image (shown in lightbox and on hover).', max_length=200)),
                ('image', models.ImageField(help_text='Upload the image. Organized by year/month in media/gallery/.', upload_to='gallery/%Y/%m/')),
                ('thumbnail', models.ImageField(blank=True, help_text='Optional smaller thumbnail. If blank, the main image is used.', null=True, upload_to='gallery/thumbnails/')),
                ('caption', models.TextField(blank=True, help_text='Short romantic caption displayed in the lightbox.')),
                ('date_taken', models.DateField(blank=True, help_text='When this photo was taken (optional).', null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Featured images are displayed larger in the masonry grid.')),
                ('is_active', models.BooleanField(default=True, help_text='Only active images are displayed on the page.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first). Images with same order sort by newest.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text="Category for filtering (e.g., 'Our Dates').", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='love.gallerycategory')),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
