# Generated by Django 6.0 on 2026-07-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('love', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoveReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="The main reason title (e.g., 'Your Smile', 'Your Eyes').", max_length=100)),
                ('description', models.TextField(help_text='The detailed romantic message revealed when the card flips.')),
                ('icon', models.CharField(default='fa-solid fa-heart', help_text='Font Awesome icon class displayed on the front of the card.', max_length=100)),
                ('emoji', models.CharField(default='💖', help_text='Decorative emoji displayed on the card front and back.', max_length=10)),
                ('gradient_class', models.CharField(default='gradient-card-1', help_text='CSS class for card gradient styling (e.g., gradient-card-1 to gradient-card-6).', max_length=50)),
                ('order', models.PositiveIntegerField(default=1, help_text='Display order (1 to 20).')),
                ('is_active', models.BooleanField(default=True, help_text='Only active reasons are displayed on the page.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Love Reason',
                'verbose_name_plural': 'Love Reasons',
                'ordering': ['order'],
            },
        ),
    ]
