# Generated by Django 6.0 on 2026-07-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('love', '0002_lovereason'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoveLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My Eternal Promise to You', help_text="Title of the letter (e.g., 'A Letter for Girlfriend's Day').", max_length=200)),
                ('date_label', models.CharField(default="August 1st — Girlfriend's Day", help_text="Display date on the letter (e.g., 'August 1, 2026').", max_length=100)),
                ('salutation', models.CharField(default='My Dearest Love,', help_text="Opening greeting (e.g., 'My Dearest Darling,').", max_length=100)),
                ('body', models.TextField(help_text='The main paragraphs of the love letter. Separate paragraphs with blank lines.')),
                ('closing', models.CharField(default='Forever and always yours,', help_text="Closing phrase before signature (e.g., 'With all my heart,').", max_length=100)),
                ('signature', models.CharField(default='Your Forever Love 💕', help_text='Signature name (animated in handwritten script).', max_length=100)),
                ('postscript', models.CharField(blank=True, default='P.S. Every second spent with you is a blessing I will cherish for a lifetime.', help_text='Optional P.S. note at the very bottom of the letter.', max_length=300)),
                ('is_active', models.BooleanField(default=True, help_text='If multiple letters exist, the newest active letter will be displayed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Love Letter',
                'verbose_name_plural': 'Love Letters',
                'ordering': ['-created_at'],
            },
        ),
    ]
