# Generated by Django 6.0 on 2026-07-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('love', '0003_loveletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountdownConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default="Counting Down to Girlfriend's Day 💕", help_text='Title displayed above the countdown timer.', max_length=200)),
                ('subtitle', models.CharField(default='Every second brings me closer to celebrating the most amazing girl in the universe.', help_text='Subtitle displayed below the title.', max_length=300)),
                ('target_date', models.DateTimeField(help_text='The exact date and time the countdown reaches zero (e.g., 2026-08-01 00:00:00).')),
                ('celebration_title', models.CharField(default="Happy Girlfriend's Day! 💖✨", help_text='Title displayed when countdown reaches zero.', max_length=200)),
                ('celebration_message', models.TextField(default='Today and every day, I celebrate YOU! You are my sunshine, my greatest blessing, and my forever love. Thank you for making my world so unimaginably beautiful 💕🌹', help_text='Romantic message displayed during the celebration animation.')),
                ('is_active', models.BooleanField(default=True, help_text='If multiple configs exist, the newest active configuration will be used.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Countdown Configuration',
                'verbose_name_plural': 'Countdown Configurations',
                'ordering': ['-created_at'],
            },
        ),
    ]
