# Generated by Django 6.0 on 2026-07-26 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('love', '0004_countdownconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountdownSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default="Counting Down to Girlfriend's Day 💕", help_text='Title displayed above the countdown timer.', max_length=200)),
                ('subtitle', models.CharField(default='Every second brings me closer to celebrating the most amazing girl in the universe.', help_text='Subtitle displayed below the title.', max_length=300)),
                ('target_date', models.DateTimeField(help_text='The exact date and time the countdown reaches zero (e.g., 2026-08-01 00:00:00).')),
                ('celebration_title', models.CharField(default="Happy Girlfriend's Day! 💖✨", help_text='Title displayed when countdown reaches zero.', max_length=200)),
                ('celebration_message', models.TextField(default='Today and every day, I celebrate YOU! You are my sunshine, my greatest blessing, and my forever love. Thank you for making my world so unimaginably beautiful 💕🌹', help_text='Romantic message displayed during the celebration animation.')),
                ('is_active', models.BooleanField(default=True, help_text='If multiple configs exist, the newest active configuration is used.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Countdown Setting',
                'verbose_name_plural': 'Countdown Settings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Title of the memory milestone (e.g., 'First Meeting', 'First Date').", max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Short romantic subtitle displayed below the title.', max_length=300)),
                ('date_label', models.CharField(help_text="Display label for the date (e.g., 'January 2024', 'Summer 2025').", max_length=100)),
                ('date_occurred', models.DateField(blank=True, help_text='Exact calendar date of this memory for chronological sorting.', null=True)),
                ('description', models.TextField(help_text='Brief summary shown on the front of the timeline card.')),
                ('expanded_content', models.TextField(blank=True, help_text='Extended heartfelt story revealed when the card is expanded on click.')),
                ('icon', models.CharField(default='fa-solid fa-heart', help_text='Font Awesome icon class for the timeline marker.', max_length=100)),
                ('emoji', models.CharField(default='💕', help_text='Decorative emoji displayed on the card.', max_length=10)),
                ('image', models.ImageField(blank=True, help_text='Upload photo for this memory (saved in media/memories/year/month/).', null=True, upload_to='memories/%Y/%m/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order on the timeline (lower numbers appear first).')),
                ('is_active', models.BooleanField(default=True, help_text='Only active memories are displayed on the website.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Memory',
                'verbose_name_plural': 'Memories',
                'ordering': ['order', 'date_occurred'],
            },
        ),
        migrations.DeleteModel(
            name='CountdownConfig',
        ),
        migrations.DeleteModel(
            name='TimelineEvent',
        ),
        migrations.AlterField(
            model_name='gallerycategory',
            name='icon',
            field=models.CharField(blank=True, default='fa-solid fa-heart', help_text='Font Awesome icon class for the category filter button.', max_length=100),
        ),
        migrations.AlterField(
            model_name='gallerycategory',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Only active categories are shown in filters.'),
        ),
        migrations.AlterField(
            model_name='gallerycategory',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order for category buttons.'),
        ),
        migrations.AlterField(
            model_name='gallerycategory',
            name='slug',
            field=models.SlugField(help_text="URL-friendly identifier (e.g., 'our-dates').", unique=True),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='caption',
            field=models.TextField(blank=True, help_text='Romantic caption displayed inside the full-screen lightbox.'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='category',
            field=models.ForeignKey(blank=True, help_text="Select a category for filtering (e.g., 'Our Dates').", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='love.gallerycategory'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='date_taken',
            field=models.DateField(blank=True, help_text='Calendar date when this photo was taken.', null=True),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(help_text='Main photo upload (stored cleanly by year/month in media/gallery/).', upload_to='gallery/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Only active photos are displayed on the website.'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured images are displayed larger in the masonry layout.'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order (lower = earlier).'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Optional smaller thumbnail for faster masonry grid loading.', null=True, upload_to='gallery/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='title',
            field=models.CharField(help_text='Title of the photo (shown in lightbox and on hover).', max_length=200),
        ),
        migrations.AlterField(
            model_name='loveletter',
            name='is_active',
            field=models.BooleanField(default=True, help_text='If multiple letters exist, the newest active letter is displayed.'),
        ),
        migrations.AlterField(
            model_name='lovereason',
            name='gradient_class',
            field=models.CharField(default='gradient-card-1', help_text='CSS class for card gradient styling (gradient-card-1 to gradient-card-6).', max_length=50),
        ),
        migrations.AlterField(
            model_name='lovereason',
            name='icon',
            field=models.CharField(default='fa-solid fa-heart', help_text='Font Awesome icon class displayed on card front.', max_length=100),
        ),
        migrations.AlterField(
            model_name='lovereason',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Only active reasons are displayed on the website.'),
        ),
        migrations.AlterField(
            model_name='lovereason',
            name='title',
            field=models.CharField(help_text="The main reason title (e.g., 'Your Smile', 'Your Kindness').", max_length=100),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='memory',
            field=models.ForeignKey(blank=True, help_text='Optional: Associate this photo with a specific milestone Memory.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_images', to='love.memory'),
        ),
        migrations.AddField(
            model_name='loveletter',
            name='memory',
            field=models.ForeignKey(blank=True, help_text='Optional: Dedicate this love letter to a specific milestone Memory.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='love_letters', to='love.memory'),
        ),
    ]
