# Generated by Django 6.0 on 2026-07-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('love', '0005_countdownsetting_memory_delete_countdownconfig_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our Romantic Symphony', help_text="Title of the music track (e.g., 'Forever Love Melody').", max_length=150)),
                ('artist', models.CharField(default='Forever Us Orchestra', help_text='Artist or composer name.', max_length=150)),
                ('audio_file', models.FileField(blank=True, help_text='Upload an audio file (MP3, WAV, OGG).', null=True, upload_to='music/')),
                ('audio_url', models.URLField(blank=True, help_text='Or provide an external direct audio URL if not uploading a file.', max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Only active music tracks are available in the music player.')),
                ('order', models.PositiveIntegerField(default=1, help_text='Playback priority order (lower numbers play first).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Background Music Track',
                'verbose_name_plural': 'Background Music Tracks',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinalSurpriseSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='One Last Question... 🌹', help_text='Title shown on the initial entrance card before clicking.', max_length=200)),
                ('hero_subtitle', models.CharField(default='We have walked through our story, our memories, and our deepest reasons. Now, there is only one thing left to ask.', help_text='Subtitle shown on the initial entrance card.', max_length=300)),
                ('trigger_button_text', models.CharField(default='Click Here ❤️', help_text='Label for the large trigger button.', max_length=100)),
                ('love_message', models.CharField(default='I Love You ❤️', help_text='The giant romantic confession revealed after clicking.', max_length=200)),
                ('question_message', models.CharField(default='Will You Stay With Me Forever?', help_text='The ultimate proposal question displayed below the giant animated heart.', max_length=300)),
                ('yes_button_text', models.CharField(default='YES ❤️', help_text='Label for the first affirmative button.', max_length=100)),
                ('always_yes_button_text', models.CharField(default='ALWAYS YES ❤️', help_text='Label for the second affirmative button.', max_length=100)),
                ('no_button_text', models.CharField(default='NO 💔', help_text='Label for the runaway button that escapes the mouse cursor.', max_length=100)),
                ('success_message', models.TextField(default="My heart is yours for all eternity! You just made me the happiest person in the universe. Happy Girlfriend's Day, my forever love! 👑💖✨", help_text='Message displayed after she clicks YES or ALWAYS YES.')),
                ('is_active', models.BooleanField(default=True, help_text='If multiple configs exist, the newest active configuration will be used.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Final Surprise Setting',
                'verbose_name_plural': 'Final Surprise Settings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecretPageSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(default='forever0801', help_text='The secret password required to unlock the sanctuary (e.g. forever0801 or your anniversary date).', max_length=100)),
                ('title', models.CharField(default='My Deepest Secret 💖', help_text='Title displayed at the top of the unlocked sanctuary.', max_length=200)),
                ('message', models.TextField(default='I Love You More Than Words Can Say ❤️', help_text='The primary romantic confession displayed in luxury typography once unlocked.')),
                ('extended_message', models.TextField(blank=True, default='You are my home, my peace, and my wildest dream come true. Every beat of my heart belongs to you, today and for all eternity. No distance, no time, and no obstacle could ever change what I feel for you. You are my forever.', help_text='Extended heartfelt note shown below the main message.')),
                ('is_active', models.BooleanField(default=True, help_text='If multiple configs exist, the newest active configuration will be used.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Secret Page Setting',
                'verbose_name_plural': 'Secret Page Settings',
                'ordering': ['-created_at'],
            },
        ),
    ]
