# Generated by Django 6.0 on 2026-07-31 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('love', '0006_backgroundmusic_finalsurprisesetting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Screen reader description for accessibility.', max_length=200),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='location',
            field=models.CharField(blank=True, help_text="Where this photo was taken (e.g., 'Paris', 'Central Park').", max_length=200),
        ),
    ]
