# Generated by Django 6.0 on 2026-07-31 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('love', '0007_galleryimage_alt_text_galleryimage_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='category',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='memory',
        ),
        migrations.DeleteModel(
            name='GalleryCategory',
        ),
        migrations.DeleteModel(
            name='GalleryImage',
        ),
    ]
